# Generated by Django 3.2.9 on 2021-12-17 12:17

import django.db.models.deletion
from django.db import migrations, models

import djangocms_frontend.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0022_auto_20180620_1551"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrontendUIItem",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="djangocms_frontend_frontenduiitem",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                ("ui_item", models.CharField(max_length=30)),
                (
                    "tag_type",
                    djangocms_frontend.fields.TagTypeField(
                        choices=[
                            ("div", "div"),
                            ("section", "section"),
                            ("article", "article"),
                            ("header", "header"),
                            ("footer", "footer"),
                            ("aside", "aside"),
                        ],
                        default="div",
                        help_text="Select the HTML tag to be used.",
                        max_length=255,
                        verbose_name="Tag type",
                    ),
                ),
                ("config", models.JSONField()),
                (
                    "attributes",
                    djangocms_frontend.fields.AttributesField(
                        blank=True, default=dict, verbose_name="Attributes"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.cmsplugin",),
        ),
    ]
